name: Matrix Demo
on: workflow_dispatch
jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        node-version: [20, 21]
        operating-system: [ubuntu-latest, windows-latest]
        include:
          - node-version: 20
            operating-system: macos-latest
        exclude:
          - node-version: 21
            operating-system: windows-latest
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Build project
        run: npm run build
